# Generated by Django 5.1.5 on 2025-05-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='custom_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
